rootProject.name = "falowp-bot-plugins"
include("falowp-bot-adapter-qq")
include("falowp-bot-adapter-cq")
include("falowp-bot-plugin-auth")
include("falowp-bot-plugin-user")
include("falowp-bot-plugin-signin")
include("falowp-bot-plugin-coin")
include("falowp-bot-plugin-bili")
include("falowp-bot-plugin-kfc")
include("falowp-bot-plugin-repeat")
include("falowp-bot-plugin-idle")
include("falowp-bot-plugin-wordcloud")
include("falowp-bot-utils-translate")
include("falowp-bot-utils-censor")
include("falowp-bot-utils-minio")
include("falowp-bot-utils-db")